# -*- coding: utf-8 -*-
"""Imersão_dados_python_aula_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DG9sht_7acgGXp78M6I-GFvlb4Fho6iG
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

df.head()

df.info()

df.describe()

df.shape

linhas, colunas = df.shape[0], df.shape[1]
print("linhas:", linhas)
print("colunas:", colunas)

df.columns

# Map original column names to Portuguese
column_translation = {
    'ano': 'ano',
    'nivel_experiencia': 'senioridade',
    'tipo_emprego': 'contrato',
    'cargo': 'cargo',
    'salario': 'salario',
    'moeda_salario': 'moeda',
    'salario_em_usd': 'usd',
    'residencia_empregado': 'residencia',
    'taxa_remoto': 'remoto',
    'localizacao_empresa': 'empresa',
    'tamanho_empresa': 'tamanho_empresa'
}

# Rename the columns
df.rename(columns=column_translation, inplace=True)

# Display the translated column names
print(df.columns)

df["senioridade"].value_counts()

df["contrato"].value_counts()

df["remoto"].value_counts()

df["tamanho_empresa"].value_counts()



# Map English categories to Portuguese
senioridade_translation = {
    'SE': 'Senior',
    'MI': 'Pleno',
    'EN': 'Junior',
    'EX': 'Executivo'
}

# Apply the translation to the 'senioridade' column
df['senioridade'] = df['senioridade'].map(senioridade_translation)

# Display the value counts of the translated column
print(df["senioridade"].value_counts())

# Map English categories to Portuguese
contrato_translation = {
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Tempo Parcial',
    'FL': 'Freelancer'
}

# Apply the translation to the 'contrato' column
df['contrato'] = df['contrato'].map(contrato_translation)

# Display the value counts of the translated column
print(df["contrato"].value_counts())

# Map English categories to Portuguese
tamanho_empresa_translation = {
    'M': 'Médio',
    'L': 'Grande',
    'S': 'Pequeno'
}

# Apply the translation to the 'tamanho_empresa' column
df['tamanho_empresa'] = df['tamanho_empresa'].map(tamanho_empresa_translation)

# Display the value counts of the translated column
print(df["tamanho_empresa"].value_counts())

# Map numerical categories to Portuguese
remoto_translation = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
}

# Apply the translation to the 'remoto' column
df['remoto'] = df['remoto'].map(remoto_translation)

# Display the value counts of the translated column
print(df["remoto"].value_counts())

df.head()

df.describe(include="object")

df.describe()

